FROM inovatrend/tomcat8-java8
ENV ARTIFACT=spring-tournament-portal
ENV VERSION=0.0.1-SNAPSHOT
COPY ./target/${ARTIFACT}-${VERSION} /opt/tomcat/webapps/${ARTIFACT}-${VERSION}
ENV PORT 8080
ENV JPDA_ADDRESS 8000
ENV JPDA_TRANSPORT dt_socket
WORKDIR /opt/tomcat/bin
COPY ./log4j.properties ./
ENTRYPOINT ["catalina.sh", "jpda", "run"]
#RUN mkdir /tmp/build/
# Add context to /tmp/build/
#ADD . /tmp/build/
EXPOSE ${PORT}
