version: "2"
services: 
 release-database-service: 
  image: mysql
  ports: 
   - "3307:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=root
  volumes:  
   - .docker-mysql-data:/var/lib/mysql
  networks: 
   -  tomcatapp-network

 web-service: 
  image: indiver/new-tournament
  environment:
   - JPDA_ADDRESS=8000
   - JPDA_TRANSPORT=dt_socket
   - spring.profiles.active=staging
   - USER_DAO=com.bo.tournament.dao.UserMgmtJpaDaoImpl
   - WEATHER_API=http://WETHER-LOAD-BALANCER-1542072245.ap-south-1.elb.amazonaws.com/status
  ports: 
   - "8080:8080"
   - "9000:8000"   
  command: "catalina.sh jpda run" 
  networks: 
   -  tomcatapp-network
  
networks:
 tomcatapp-network:
  driver: bridge 